package com.gitlabflow.floworchestrator.common.errors;

public enum ErrorCode {
    VALIDATION,
    INTEGRATION_BAD_REQUEST,
    INTEGRATION_UNAUTHORIZED,
    INTEGRATION_FORBIDDEN,
    INTEGRATION_NOT_FOUND,
    INTEGRATION_RATE_LIMITED,
    INTEGRATION_UNAVAILABLE,
    INTEGRATION_UNKNOWN,
    UNKNOWN
}
