@baseUrl = http://localhost:8080

### Default request (no body)
POST {{baseUrl}}/api/issues

### Filtered request
POST {{baseUrl}}/api/issues
Content-Type: application/json

{
	"pagination": {
		"page": 2,
		"perPage": 20
	},
	"filters": {
		"state": "opened",
		"labels": ["bug"],
		"assignee": ["john.doe"],
		"milestone": ["M1"]
	}
}

### Invalid request (multiple labels)
POST {{baseUrl}}/api/issues
Content-Type: application/json

{
	"filters": {
		"labels": ["bug", "infra"]
	}
}
