spring:
  application:
    name: FlowOrchestrator
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

app:
  issues-api:
    default-page-size: 40
    max-page-size: 100
